/*
 * Babylon Core API - RCnet v3.1
 * This API is exposed by the Babylon Radix node to give clients access to the Radix Engine, Mempool and State in the node.  It is intended for use by node-runners on a private network, and is not intended to be exposed publicly. Very heavy load may impact the node's function.  This API exposes queries against the node's current state (see `/lts/state/` or `/state/`), and streams of transaction history (under `/lts/stream/` or `/stream`).  If you require queries against snapshots of historical ledger state, you may also wish to consider using the [Gateway API](https://docs-babylon.radixdlt.com/).  ## Integration and forward compatibility guarantees  This version of the Core API belongs to the fourth release candidate of the Radix Babylon network (\"RCnet v3.1\").  Integrators (such as exchanges) are recommended to use the `/lts/` endpoints - they have been designed to be clear and simple for integrators wishing to create and monitor transactions involving fungible transfers to/from accounts.  All endpoints under `/lts/` are guaranteed to be forward compatible to Babylon mainnet launch (and beyond). We may add new fields, but existing fields will not be changed. Assuming the integrating code uses a permissive JSON parser which ignores unknown fields, any additions will not affect existing code. 
 *
 * The version of the OpenAPI document: 0.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package live.radix.core.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * LtsTransactionSubmitRequest
 */
@JsonPropertyOrder({
  LtsTransactionSubmitRequest.JSON_PROPERTY_NETWORK,
  LtsTransactionSubmitRequest.JSON_PROPERTY_NOTARIZED_TRANSACTION_HEX,
  LtsTransactionSubmitRequest.JSON_PROPERTY_FORCE_RECALCULATE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-18T09:57:43.738813900+03:00[Europe/Kiev]")
public class LtsTransactionSubmitRequest {
  public static final String JSON_PROPERTY_NETWORK = "network";
  private String network;

  public static final String JSON_PROPERTY_NOTARIZED_TRANSACTION_HEX = "notarized_transaction_hex";
  private String notarizedTransactionHex;

  public static final String JSON_PROPERTY_FORCE_RECALCULATE = "force_recalculate";
  private Boolean forceRecalculate;

  public LtsTransactionSubmitRequest() {
  }

  public LtsTransactionSubmitRequest network(String network) {
    
    this.network = network;
    return this;
  }

   /**
   * The logical name of the network
   * @return network
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNetwork() {
    return network;
  }


  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNetwork(String network) {
    this.network = network;
  }


  public LtsTransactionSubmitRequest notarizedTransactionHex(String notarizedTransactionHex) {
    
    this.notarizedTransactionHex = notarizedTransactionHex;
    return this;
  }

   /**
   * A hex-encoded, compiled notarized transaction.
   * @return notarizedTransactionHex
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NOTARIZED_TRANSACTION_HEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNotarizedTransactionHex() {
    return notarizedTransactionHex;
  }


  @JsonProperty(JSON_PROPERTY_NOTARIZED_TRANSACTION_HEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNotarizedTransactionHex(String notarizedTransactionHex) {
    this.notarizedTransactionHex = notarizedTransactionHex;
  }


  public LtsTransactionSubmitRequest forceRecalculate(Boolean forceRecalculate) {
    
    this.forceRecalculate = forceRecalculate;
    return this;
  }

   /**
   * If true, the transaction validity is freshly recalculated without using any caches (defaults false)
   * @return forceRecalculate
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FORCE_RECALCULATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isForceRecalculate() {
    return forceRecalculate;
  }


  @JsonProperty(JSON_PROPERTY_FORCE_RECALCULATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setForceRecalculate(Boolean forceRecalculate) {
    this.forceRecalculate = forceRecalculate;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LtsTransactionSubmitRequest ltsTransactionSubmitRequest = (LtsTransactionSubmitRequest) o;
    return Objects.equals(this.network, ltsTransactionSubmitRequest.network) &&
        Objects.equals(this.notarizedTransactionHex, ltsTransactionSubmitRequest.notarizedTransactionHex) &&
        Objects.equals(this.forceRecalculate, ltsTransactionSubmitRequest.forceRecalculate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(network, notarizedTransactionHex, forceRecalculate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LtsTransactionSubmitRequest {\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    notarizedTransactionHex: ").append(toIndentedString(notarizedTransactionHex)).append("\n");
    sb.append("    forceRecalculate: ").append(toIndentedString(forceRecalculate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `network` to the URL query string
    if (getNetwork() != null) {
      try {
        joiner.add(String.format("%snetwork%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNetwork()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `notarized_transaction_hex` to the URL query string
    if (getNotarizedTransactionHex() != null) {
      try {
        joiner.add(String.format("%snotarized_transaction_hex%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNotarizedTransactionHex()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `force_recalculate` to the URL query string
    if (isForceRecalculate() != null) {
      try {
        joiner.add(String.format("%sforce_recalculate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(isForceRecalculate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

